#164691211 Setup and deploy base application to Heroku
aqua-organisation/ah-django-Aqua pull request #8
Opened 2019-03-25 22:06 UTC by richien

#### What does this PR do?

Add setup files for deploying the application to Heroku

#### Description of Task to be completed?

- add a Procfile to tell Heroku how to run the app
- install django_heroku for configuring settings with Heroku
- install gunicorn
- update the requirements.txt file with references to the newly
installed packages

#### How should this be manually tested?

- URLS: 
```Staging``` [https://ah-django-aqua-staging.herokuapp.com/api/](https://ah-django-aqua-staging.herokuapp.com/api/)
```Production```[https://ah-django-aqua.herokuapp.com/api/](https://ah-django-aqua.herokuapp.com/api/)
- Open up a rest client like postman and register with the application using either of the urls above and 
the urls above. Refer to the README.md file for the structure of the request body.

#### Any background context you want to provide?

- There are two applications deployed; one for the staging environment and the other for production.
- The url for the staging environment is suffixed with ``` -staging ``` to differentiate it from the production
url.

#### What are the relevant pivotal tracker stories?

[#164691211](https://www.pivotaltracker.com/story/show/164691211)

#### Screenshots (if appropriate)

![heroku-staging-login](https://user-images.githubusercontent.com/6644707/54957196-17226f00-4f63-11e9-868b-3f260ad1c877.PNG)

2019-03-26 13:51 UTC, RonKbS commented
Kindly share the source (article or the like) you used to come up with this implementation in your PR description.

2019-03-26 15:24 UTC, reifred approved these changes
@richien I have tested the application and it is working fine. Thanks for the work

2019-03-26 21:52 UTC, richien commented
> 
> 
> Kindly share the source (article or the like) you used to come up with this implementation in your PR description.

This has been done. Kindly refer to the Resources section of the PR for links to the resources I used.

2019-03-27 14:15 UTC, NicholusMuwonge approved these changes
Just tested the links and they work flawlessly. Nice work @richien

2019-03-28 07:11 UTC, RonKbS requested changes
Please, make the secret_key be picked up from the environment.

2019-03-28 08:11 UTC, richien commented
> 
> 
> Please, make the secret_key be picked up from the environment.

Thank you for the feedback. This has been done.

2019-03-28 12:17 UTC, richien commented
> 
> 
> > Thank you for the feedback. This has been done.
> 
> Kindly elaborate on how you've implemented the change because the key is still in the settings file.

I generated a new SECRET_KEY using the python package secret i.e. I run the command ``` secret.token_hex(24) ``` from the python interpreter. I then copied the generated string and created a SECRET_KEY env variable in the application's settings on heroku.com, and used the string as the value.

2019-03-28 12:20 UTC, RonKbS commented
> I generated a new SECRET_KEY using the python package secret i.e. I run the command secret.token_hex(24) from the python interpreter. I then copied the generated string and created a SECRET_KEY env variable in the application's settings on heroku.com, and used the string as the value.

That's all good @richien. However, you have not included how our Django application is to pick up that secret key in the implementation introduced by this PR.

2019-03-28 12:30 UTC, richien commented
> 
> 
> > I generated a new SECRET_KEY using the python package secret i.e. I run the command secret.token_hex(24) from the python interpreter. I then copied the generated string and created a SECRET_KEY env variable in the application's settings on heroku.com, and used the string as the value.
> 
> That's all good @richien. However, you have not included how our Django application is to pick up that secret key in the implementation introduced by this PR.

I have made an amendment to the PR description to include this step.

2019-03-28 12:36 UTC, RonKbS commented
> I have made an amendment to the PR description to include this step.

I am referring to line 22 in the settings.py file

2019-03-28 13:23 UTC, richien commented
> 
> 
> > I have made an amendment to the PR description to include this step.
> 
> I am referring to line 22 in the settings.py file

I have added information on how to set the SECRET_KEY environment variable locally under the `Any Background Context you want to provide`. The reason this is added at this location and not in the `How to manually test this` section is that the tests for this implementation are meant to be done on the deployed application, accessible on the URLs shared in the tests section.

2019-03-28 14:04 UTC, richien commented
> > I have made an amendment to the PR description to include this step.
> 
> I am referring to line 22 in the settings.py file

I have noticed my mistake and made the amendnent. Thank you

2019-03-28 18:16 UTC, RonKbS approved these changes

2019-03-28 18:17 UTC, merged